/**
 * Lugares conocidos de Manizales para el buscador del pasajero mientras no esté el servicio de direcciones con
 * OpenStreetMap (ADR-0002, Photon). Las coordenadas son aproximadas: sirven para probar el flujo completo, no
 * para operar. Cada lugar lleva el barrio o zona, que es lo único que ve el conductor del destino antes de aceptar (D-11).
 */
export type TipoLugar =
  'barrio' | 'comercio' | 'salud' | 'educacion' | 'transporte' | 'parque' | 'turismo';

export interface LugarConocido {
  id: string;
  nombre: string;
  barrio: string;
  tipo: TipoLugar;
  lat: number;
  lng: number;
  /** Otros nombres con los que la gente lo busca. */
  alias?: string[];
}

export const LUGARES_MANIZALES: readonly LugarConocido[] = [
  // Centro
  {
    id: 'catedral',
    nombre: 'Catedral Basílica de Manizales',
    barrio: 'Centro',
    tipo: 'turismo',
    lat: 5.0689,
    lng: -75.5174,
    alias: ['catedral', 'plaza de bolivar', 'centro'],
  },
  {
    id: 'parque-caldas',
    nombre: 'Parque Caldas',
    barrio: 'Centro',
    tipo: 'parque',
    lat: 5.0702,
    lng: -75.5201,
    alias: ['parque de caldas'],
  },
  {
    id: 'alcaldia',
    nombre: 'Alcaldía de Manizales',
    barrio: 'Centro',
    tipo: 'comercio',
    lat: 5.0684,
    lng: -75.5167,
  },
  {
    id: 'gobernacion',
    nombre: 'Gobernación de Caldas',
    barrio: 'Centro',
    tipo: 'comercio',
    lat: 5.0691,
    lng: -75.5172,
  },
  {
    id: 'teatro-los-fundadores',
    nombre: 'Teatro Los Fundadores',
    barrio: 'Centro',
    tipo: 'turismo',
    lat: 5.0679,
    lng: -75.5189,
  },
  {
    id: 'cable-aereo-centro',
    nombre: 'Cable Aéreo Manizales (Los Cámbulos)',
    barrio: 'Los Cámbulos',
    tipo: 'transporte',
    lat: 5.0744,
    lng: -75.4909,
    alias: ['cable aereo', 'cable'],
  },
  {
    id: 'plaza-de-mercado',
    nombre: 'Plaza de Mercado de Manizales',
    barrio: 'Centro',
    tipo: 'comercio',
    lat: 5.0668,
    lng: -75.5208,
  },
  // Palogrande, Cable, zona sur-oriental
  {
    id: 'estadio-palogrande',
    nombre: 'Estadio Palogrande',
    barrio: 'Palogrande',
    tipo: 'turismo',
    lat: 5.0536,
    lng: -75.4967,
    alias: ['estadio'],
  },
  {
    id: 'universidad-nacional',
    nombre: 'Universidad Nacional (Sede Palogrande)',
    barrio: 'Palogrande',
    tipo: 'educacion',
    lat: 5.0553,
    lng: -75.4909,
    alias: ['nacional', 'unal'],
  },
  {
    id: 'universidad-de-manizales',
    nombre: 'Universidad de Manizales',
    barrio: 'Versalles',
    tipo: 'educacion',
    lat: 5.0625,
    lng: -75.4945,
    alias: ['umanizales'],
  },
  {
    id: 'universidad-de-caldas',
    nombre: 'Universidad de Caldas (Sede Central)',
    barrio: 'Centro',
    tipo: 'educacion',
    lat: 5.0704,
    lng: -75.5206,
    alias: ['ucaldas'],
  },
  {
    id: 'universidad-autonoma',
    nombre: 'Universidad Autónoma de Manizales',
    barrio: 'Antigua',
    tipo: 'educacion',
    lat: 5.0478,
    lng: -75.4846,
    alias: ['autonoma'],
  },
  {
    id: 'universidad-catolica',
    nombre: 'Universidad Católica de Manizales',
    barrio: 'Chipre',
    tipo: 'educacion',
    lat: 5.0745,
    lng: -75.5262,
  },
  {
    id: 'hospital-de-caldas',
    nombre: 'Hospital Universitario de Caldas',
    barrio: 'Palogrande',
    tipo: 'salud',
    lat: 5.0577,
    lng: -75.4972,
    alias: ['hospital'],
  },
  {
    id: 'clinica-san-marcel',
    nombre: 'Clínica San Marcel',
    barrio: 'La Estrella',
    tipo: 'salud',
    lat: 5.0608,
    lng: -75.4888,
  },
  {
    id: 'clinica-la-presentacion',
    nombre: 'Clínica La Presentación',
    barrio: 'Versalles',
    tipo: 'salud',
    lat: 5.0631,
    lng: -75.5019,
  },
  {
    id: 'sede-sena',
    nombre: 'SENA Manizales',
    barrio: 'La Enea',
    tipo: 'educacion',
    lat: 5.0384,
    lng: -75.4804,
    alias: ['sena'],
  },
  // Comercio
  {
    id: 'mall-plaza',
    nombre: 'Mall Plaza Manizales',
    barrio: 'Fundadores',
    tipo: 'comercio',
    lat: 5.0547,
    lng: -75.4796,
    alias: ['mall'],
  },
  {
    id: 'fundadores',
    nombre: 'Centro Comercial Fundadores',
    barrio: 'Fundadores',
    tipo: 'comercio',
    lat: 5.0637,
    lng: -75.4893,
  },
  {
    id: 'cable-plaza',
    nombre: 'Centro Comercial Cable Plaza',
    barrio: 'Cable',
    tipo: 'comercio',
    lat: 5.0626,
    lng: -75.4853,
  },
  {
    id: 'sancancio',
    nombre: 'Centro Comercial Sancancio',
    barrio: 'Sancancio',
    tipo: 'comercio',
    lat: 5.0703,
    lng: -75.5004,
  },
  {
    id: 'carrefour',
    nombre: 'Centro Comercial Caldas Plaza',
    barrio: 'Chipre',
    tipo: 'comercio',
    lat: 5.0731,
    lng: -75.5187,
  },
  {
    id: 'exito-chipre',
    nombre: 'Éxito Chipre',
    barrio: 'Chipre',
    tipo: 'comercio',
    lat: 5.0752,
    lng: -75.5287,
  },
  {
    id: 'exito-versalles',
    nombre: 'Éxito Versalles',
    barrio: 'Versalles',
    tipo: 'comercio',
    lat: 5.0642,
    lng: -75.5021,
  },
  // Transporte
  {
    id: 'terminal',
    nombre: 'Terminal de Transportes de Manizales',
    barrio: 'La Francia',
    tipo: 'transporte',
    lat: 5.0546,
    lng: -75.4815,
    alias: ['terminal', 'terminal de transportes'],
  },
  {
    id: 'aeropuerto',
    nombre: 'Aeropuerto La Nubia',
    barrio: 'La Nubia',
    tipo: 'transporte',
    lat: 5.0296,
    lng: -75.4647,
    alias: ['aeropuerto', 'la nubia'],
  },
  {
    id: 'terminal-cable',
    nombre: 'Estación Cable Aéreo Fundadores',
    barrio: 'Fundadores',
    tipo: 'transporte',
    lat: 5.0651,
    lng: -75.4867,
  },
  // Parques y turismo
  {
    id: 'chipre-mirador',
    nombre: 'Mirador de Chipre',
    barrio: 'Chipre',
    tipo: 'turismo',
    lat: 5.0738,
    lng: -75.5311,
    alias: ['chipre', 'mirador'],
  },
  {
    id: 'monumento-colonizadores',
    nombre: 'Monumento a los Colonizadores',
    barrio: 'Chipre',
    tipo: 'turismo',
    lat: 5.0741,
    lng: -75.5296,
    alias: ['colonizadores'],
  },
  {
    id: 'recinto-del-pensamiento',
    nombre: 'Recinto del Pensamiento',
    barrio: 'Vía al Magdalena',
    tipo: 'turismo',
    lat: 5.0332,
    lng: -75.4412,
    alias: ['recinto'],
  },
  {
    id: 'jardin-botanico',
    nombre: 'Jardín Botánico Universidad de Caldas',
    barrio: 'Sancancio',
    tipo: 'parque',
    lat: 5.0441,
    lng: -75.4984,
  },
  {
    id: 'parque-bicentenario',
    nombre: 'Parque del Bicentenario',
    barrio: 'Palogrande',
    tipo: 'parque',
    lat: 5.0562,
    lng: -75.4949,
  },
  {
    id: 'feria-expocaldas',
    nombre: 'Expoferias',
    barrio: 'Los Cedros',
    tipo: 'turismo',
    lat: 5.0522,
    lng: -75.4952,
  },
  // Barrios
  {
    id: 'barrio-palogrande',
    nombre: 'Palogrande',
    barrio: 'Palogrande',
    tipo: 'barrio',
    lat: 5.0548,
    lng: -75.4945,
  },
  {
    id: 'barrio-chipre',
    nombre: 'Barrio Chipre',
    barrio: 'Chipre',
    tipo: 'barrio',
    lat: 5.0748,
    lng: -75.5278,
  },
  {
    id: 'barrio-la-enea',
    nombre: 'La Enea',
    barrio: 'La Enea',
    tipo: 'barrio',
    lat: 5.0409,
    lng: -75.4783,
  },
  {
    id: 'barrio-milan',
    nombre: 'Milán',
    barrio: 'Milán',
    tipo: 'barrio',
    lat: 5.0498,
    lng: -75.5047,
  },
  {
    id: 'barrio-versalles',
    nombre: 'Versalles',
    barrio: 'Versalles',
    tipo: 'barrio',
    lat: 5.0634,
    lng: -75.5003,
  },
  {
    id: 'barrio-sancancio',
    nombre: 'Sancancio',
    barrio: 'Sancancio',
    tipo: 'barrio',
    lat: 5.0687,
    lng: -75.5036,
  },
  {
    id: 'barrio-la-francia',
    nombre: 'La Francia',
    barrio: 'La Francia',
    tipo: 'barrio',
    lat: 5.0586,
    lng: -75.4752,
  },
  {
    id: 'barrio-los-rosales',
    nombre: 'Los Rosales',
    barrio: 'Los Rosales',
    tipo: 'barrio',
    lat: 5.0627,
    lng: -75.5091,
  },
  {
    id: 'barrio-san-jose',
    nombre: 'San José',
    barrio: 'San José',
    tipo: 'barrio',
    lat: 5.0753,
    lng: -75.5149,
  },
  {
    id: 'barrio-bosques-del-norte',
    nombre: 'Bosques del Norte',
    barrio: 'Bosques del Norte',
    tipo: 'barrio',
    lat: 5.0822,
    lng: -75.5117,
  },
  {
    id: 'barrio-villapilar',
    nombre: 'Villapilar',
    barrio: 'Villapilar',
    tipo: 'barrio',
    lat: 5.0791,
    lng: -75.5231,
  },
  {
    id: 'barrio-la-linda',
    nombre: 'La Linda',
    barrio: 'La Linda',
    tipo: 'barrio',
    lat: 5.0471,
    lng: -75.5129,
  },
  {
    id: 'barrio-estrella',
    nombre: 'La Estrella',
    barrio: 'La Estrella',
    tipo: 'barrio',
    lat: 5.0596,
    lng: -75.4864,
  },
  {
    id: 'barrio-el-cable',
    nombre: 'El Cable',
    barrio: 'Cable',
    tipo: 'barrio',
    lat: 5.0627,
    lng: -75.4876,
  },
  {
    id: 'barrio-campohermoso',
    nombre: 'Campohermoso',
    barrio: 'Campohermoso',
    tipo: 'barrio',
    lat: 5.0731,
    lng: -75.5117,
  },
  {
    id: 'barrio-la-sultana',
    nombre: 'La Sultana',
    barrio: 'La Sultana',
    tipo: 'barrio',
    lat: 5.0588,
    lng: -75.5083,
  },
];
